# Generated by Django 5.0.2 on 2024-02-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[("room", "Room"), ("experience", "Experience")],
                max_length=15,
                null=True,
            ),
        ),
    ]
