# Generated by Django 5.0.2 on 2024-02-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_reservation_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="kind",
            field=models.CharField(
                choices=[("room", "Room"), ("experience", "Experience")],
                max_length=15,
                null=True,
            ),
        ),
    ]
