# Generated by Django 5.0.2 on 2024-02-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0004_rename_end_experience_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
