# Generated by Django 5.0.2 on 2024-02-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0005_experience_end_experience_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="duration",
            field=models.DurationField(),
        ),
    ]
