# Generated by Django 5.0.2 on 2024-02-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0006_alter_experience_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="duration",
            field=models.TimeField(),
        ),
    ]
