# Generated by Django 5.0.2 on 2024-02-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_experience_category_alter_experience_perks_and_more"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="experience",
            field=models.ManyToManyField(to="experiences.experience"),
        ),
    ]
