# Generated by Django 5.0.2 on 2024-02-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0002_wishlist_experience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="experience",
            new_name="experiences",
        ),
        migrations.RenameField(
            model_name="wishlist",
            old_name="room",
            new_name="rooms",
        ),
    ]
